ethdebug/format

docs/source/known-challenges.md

When writing this up initially, I didn't bother to include this section, but I think it's worth including.
(I accidentally at first directly pushed this to main, oops, but I reverted it...)

Add section about markings for mapping keys

---

.github/workflows/ci.yml
docs/source/conf.py

More strict checks when building docs. Could end up being annoying, but we run with this enabled by default in Solidity and so far did not run into anything that would make us seriously consider disabling it.

Enable nitpicky-mode and warnings-as-errors in Sphinx

---

docs/source/index.md

CI checks in other PRs are failing because the format spec is not included in the index.

Add `format.md` to the index

---

docs/source/format.md

While reading the spec I found a few typos.

Fix typos in format spec

---

.github/workflows/ci.yml

To preview the docs you visit the action and download the zip with HTML docs. You can unpack and view `index.html` in a browser locally.
It would be more convenient if we could upload the directory directly, without packing it. That's what we do in Solidity on CircleCI, and there you can just go directly to `index.html` in the browser. Having a zip is less convenient but probably still good enough.

Upload built Sphinx docs as artifact to allow previewing them on a PR

---

docs/source/format.md

Clarifies that the position given in `arguments` information gives the index into the (well-ordered) formal parameter list. Tagging @cameel because I can't request a review?
Closes #29

#29 Attempts to clarify position field for arguments

---

web/spec/sketches/layout.mdx

OK, I finally sat down and banged this out.  Attempts to address #31.  Tried to cover everything that seemed reasonable.  Did this primarily in prose rather than listing out object structures and field names and such, hope that's OK.  Lot of uncertainty on a number of points but I hope despite that this is concrete enough to work with -- not to use I mean, but to work on without having to figure out any more fuzzy indefinite points, that the remaining questions are contained to discrete points.
(I guess there's perhaps one exception to this, which is the question of primitive types.  Oh well.)
I think this does an OK job at all three goals?  There's more I would maybe have liked to included to be more general but it didn't seem practical.  I don't know, I'll let you all figure out whether …

Add draft of what layout description might look like

---

schemas/type/base.schema.yaml
web/docusaurus.config.ts
web/package.json
web/spec/overview.mdx
web/spec/type/_category_.json
web/spec/type/base.mdx
web/spec/type/overview.mdx
web/spec/type/type.mdx
web/src/components/SchemaViewer.tsx
web/src/loadSchema.ts
web/yarn.lock

This PR proposes to define the **ethdebug/format/type/base** schema to serve as a minimally-necessary schema for all type representations, to be extended by more-specific subschemas for known kinds of types. This PR also proposes a future **ethdebug/format/type** schema that will extend **ethdebug/format/type/base**.
This takes the organization approach to do the following:
- Define a base schema that doesn't know about uints or strings, etc. It defines the syntactic form of elementary types vs. complex types (types that compose other types). [I imagine we'll add algebraic types to this distinction soon]
- Define a canonical type schema that imposes restrictions on known kinds of types, like to assert that uint types must be specified with a certain number of bits.
For this PR, only the …

Specify ethdebug/format/type/base

---

web/package.json
web/src/components/SchemaViewer.tsx
web/src/contexts/SchemaContext.tsx
web/src/schemas.ts
web/src/theme/JSONSchemaViewer/JSONSchemaElements/SchemaConditional/schemaConditional.tsx
web/src/theme/JSONSchemaViewer/JSONSchemaElements/schemaComposition/allOfSchema.tsx
web/src/theme/JSONSchemaViewer/components/CreateNodes.tsx
web/yarn.lock

- Use new docusaurus-json-schema-plugin version with support for components knowing their own pointer and depth level
- Define "schema index" to allow schemas to have a canonical URL
- When rendering a subschema, check if it has a canonical URL in the index and render a link to that page instead of the full subschema
- Preprocess schemas to add an internal ID field to every object recursively in the schema. Use this ID field when checking against schema index.
- Remove "Conditional subschemas" dropdown that wraps if/then/else constructs
- Define a custom `{ allOf: { if, then } }` detection system to recognize this common pattern for implementing discriminators

Customize schema component rendering

---

schemas/type/base.schema.yaml
schemas/type/complex/alias.schema.yaml
schemas/type/complex/struct.schema.yaml
schemas/type/definition.schema.yaml
schemas/type/elementary/contract.schema.yaml
schemas/type/elementary/enum.schema.yaml
tests/src/schemas.ts
web/spec/type/concepts.mdx
web/src/schemas.ts

This PR adds a new `definition` field to alias, struct, contract, and enum types, referencing a new **ethdebug/format/type/definition** schema.

Allow types to have definitions

---

schemas/type/complex/mapping.schema.yaml
schemas/type/complex/struct.schema.yaml
schemas/type/complex/tuple.schema.yaml
schemas/type/elementary/contract.schema.yaml
web/spec/type/concepts.mdx

... particularly around the use of titles for subschemas

Improve schema consistency

---

web/src/theme/JSONSchemaViewer/utils/generateFriendlyName.tsx

... because no one wants to have to drill down for such minimal extra signal

Render const values in schema dropdown summaries

---

schemas/type/complex.schema.yaml
schemas/type/complex/function.schema.yaml
tests/src/schemas.ts
web/spec/type/complex/function.mdx
web/src/schemas.ts

- Use `contains` object mapping style for `parameters` types and `returns` types. Force `parameters` to be a type wrapper around a tuple type (and allow `returns` to be any other kind of type)
- Define one-of required fields `internal: true` xor `external: true`.
- Override external types `contains` field to also allow a `contract` field (for the contract in which an external function type is defined)

Define function types

---

packages/web/docusaurus.config.ts

Show "edit this page" link on all docs/spec pages

---

bin/start

Since jest's default --watch does not appear to detect changes to the schemas (or at least it doesn't realize that those changes affect the test results)

Run `yarn start` with jest's `--watchAll` flag

---

packages/tests/src/loadSchemas.ts

(`VERBOSE` mode reported every check, even ones that were valid. Now, when examples fail validation, the tests will only show information about the failed schema checks. Much less noise.)

Switch tests validation output to DETAILED

---

packages/web/package.json
packages/web/src/contexts/SchemaContext.tsx
packages/web/src/theme/JSONSchemaViewer/JSONSchemaElements/schemaComposition/DiscriminatorSchema.tsx
packages/web/src/theme/JSONSchemaViewer/JSONSchemaElements/schemaComposition/allOfSchema.tsx
packages/web/src/theme/JSONSchemaViewer/components/CreateNodes.tsx
packages/web/tsconfig.json

Background: I previously added some janky code for detecting this format's conventional use of polymorphic discriminators (using `allOf` with `if: { properties: { const: ... } }`, the idea being to render these in a custom manner (different than docusaurus-json-schema-plugin's default `allOf` rendering).
This PR cleans up that code (which currently just lives in a swizzled `AllOfSchema` component), so that it has its own module with a `detectDiscriminator()` function and well-typed components, etc.
I'm making this change so that it won't get so bad when this project finds other schema conventions that make sense and we want to be able to custom-detect our use of the convention and render it properly.
This PR adds json-schema-typed to the web package and also enables `strict: true`, so …

Cleanup schema explorer override code for polymorphic discriminators

---

packages/format/bin/generate-schema-yamls.js
packages/format/src/index.ts
packages/format/src/schemas.ts
packages/web/spec/type/concepts.mdx
packages/web/src/components/SchemaViewer.tsx

This PR adds a `Schema<Id>` helper type as an export of @ethdebug/format. This provides all the schemas at the type-level (e.g., `Schema<"schema:ethdebug/format/type">` equals `{ readonly $schema: string; readonly $id: string; /* ... */ }`).
This sort of thing is necessary because TypeScript is not capable of inferring `const` types except for value literals... so this PR modifies the existing schema-to-module codegen process to stringify each schema as an object literal (in addition to the existing output of all the YAMLs as string literals). This new object dump is initialized with our friend `as const`.
Anyway, this sort of thing is a bit extraneous, but I figured it couldn't hurt. Having these raw schema const types is necessary for certain general-purpose solutions like …

Export schemas at type-level and improve a few other things slightly

---

packages/web/src/theme/JSONSchemaViewer/JSONSchemaElements/schemaComposition/ExclusiveRequiredPropertiesSchema.tsx
packages/web/src/theme/JSONSchemaViewer/JSONSchemaElements/schemaComposition/allOfSchema.tsx

- Assume the pattern
```yaml
allOf:
- oneOf:
- required:
- ...
- ...
- if:
required:
- ...
then:
...
- ...
```
to be the canonical form for ethdebug/format schemas to represent the concept of schemas that are defined with different subschemas depending on which set of mutually-exclusive required properties are included
- Detect this pattern
- Display it with custom wording instead of the default docusaurus-json-schema-plugin presentation of `allOf`s and such

Improve display of schemas with mutually-exclusive required properties

---

packages/web/src/components/SchemaViewer.tsx
packages/web/src/theme/JSONSchemaViewer/components/CreateNodes.tsx
packages/web/src/theme/JSONSchemaViewer/components/UnnecessaryComposition.tsx

For any schema that defines a `$ref` property alongside any other properties, docusaurus-json-schema-plugin currently loses all other properties and treats the schema as just the $ref'd other schema itself. This is because docusaurus-json-schema-plugin uses the now-unmaintained @stoplight/json-ref-resolver, which is stuck on the old JSON Schema drafts 4-7 semantics. (In those older drafts, this behavior was correct.)
To work around this issue:
- Expand the existing schema preprocessing logic to detect all $ref's with siblings
- For each such case, replace the `{ $ref: "...", ...props }` with that $ref moved into an available schema composition keyword. (e.g., it might become `{ ...props, allOf: [{ $ref: "..." }] }`).
- Throw an error if the schema uses all three composition keywords and …

Hack around limitation that prevents `$ref: ...`s from having siblings

---

packages/web/src/contexts/SchemaContext.tsx
packages/web/src/theme/JSONSchemaViewer/components/CreateNodes.tsx
packages/web/src/theme/JSONSchemaViewer/components/UnnecessaryComposition.tsx

- Link directly to schemas with doc section links in index
- Ignore matching `type`s when determining if `type` is included for semantic purposes in an extension schema
- Cleanup imports and define a handy type for schemas with internal IDs

Improve schema extension rendering

---

schemas/pointer.schema.yaml

✨ feat(Pointer Schema): Better validation errors for pointer schema. 

---

packages/web/spec/pointer/collection/scope.mdx
packages/web/src/schemas.ts
schemas/pointer.schema.yaml
schemas/pointer/collection.schema.yaml
schemas/pointer/collection/scope.schema.yaml
schemas/pointer/expression.schema.yaml

To avoid unnecessary duplication in large pointer representations, this adds a new ethdebug/format/pointer/collection schema, i.e. `{ define: { [identifier]: expression }, in: pointer }`

Add scope collection to pointer schema and fix storage string pointer example

---

packages/pointers/src/data.ts
packages/pointers/src/dereference/index.test.ts
packages/pointers/src/dereference/process.ts
packages/pointers/src/evaluate.test.ts
packages/pointers/src/evaluate.ts
packages/pointers/src/pointer.test.ts
packages/pointers/src/pointer.ts
packages/pointers/test/ganache.ts
packages/web/docs/implementation-guides/pointers/evaluating-expressions.mdx
packages/web/spec/pointer/expression.mdx
packages/web/src/schemas.ts
schemas/pointer.schema.yaml
schemas/pointer/expression.schema.yaml

The **ethdebug/format/pointer/expression** did not define any notion of bytes width for any expressions, leaving it to implementors to guess how many bytes should be used when representing the evaluation of a given expression.
This PR addresses that concern by defining an explicit `{ "$sized<N>": <expression> }` expression that resolves to the resized (left-padded or left-truncated) equivalent of its subexpression.

Address specification deficiency around expression bytes width

---

packages/pointers/src/evaluate.test.ts
packages/pointers/src/evaluate.ts
packages/pointers/src/pointer.ts
schemas/pointer.schema.yaml
schemas/pointer/expression.schema.yaml

To serve as syntactic sugar in place of specifying 32 or 0x20 or whatever. This mirrors the `"$wordsize"` constant expression.

Add { $wordsized: <expression> } expression

---

packages/pointers/src/test-cases.ts
packages/web/docs/implementation-guides/pointers/testing/test-cases.mdx
schemas/pointer.schema.yaml

- Redo the struct memory example as struct storage
- Add a test case for it with Solidity code and such
- Include this in the documentation

Test and document the testing of pointers to structs in storage

---

packages/web/docs/implementation-guides/pointers/testing/test-cases.mdx
packages/web/src/components/CodeListing.tsx
packages/web/src/components/LinkedCodeBlock.tsx
packages/web/src/css/custom.css

Add code block hyperlinks to each test case documentation

---

packages/web/spec/data/_category_.json
packages/web/spec/materials/_category_.json
packages/web/spec/pointer/_category_.json
packages/web/spec/pointer/collection/_category_.json
packages/web/spec/pointer/region/_category_.json
packages/web/spec/type/_category_.json

... since these pages are rather useless without adding proper descriptions for everything.

Remove autogenerated category pages from spec

---

packages/pointers/src/dereference/generate.ts
packages/pointers/src/dereference/index.test.ts
packages/pointers/src/dereference/index.ts
packages/pointers/src/dereference/process.ts
packages/pointers/src/pointer.test.ts
packages/pointers/src/pointer.ts
packages/pointers/test/observe.ts
packages/web/spec/pointer/template.mdx
packages/web/src/schemas.ts
schemas/pointer/collection.schema.yaml
schemas/pointer/collection/reference.schema.yaml
schemas/pointer/template.schema.yaml

This PR introduces pointer templates, allowing the re-use of similar pointers without requiring that compilers output full pointer representations for every re-use.
This uses the existing pointer expression system to define pointer templates essentially as lambda functions.
This PR updates the schemas, the spec website, and adds support for pointer templates in the reference implementation.

Define pointer templates

---

.github/workflows/gh-pages.yml
packages/web/docusaurus.config.ts

- Use just `/` as default baseUrl
- Update gh-pages action to override this

Allow overriding Docusaurus baseUrl

---

packages/web/src/schemas.ts

So that these schemas correctly link to one another and do not compose references wholly.

Add program schemas to website schema index

---

packages/web/docs/sketches/layout.mdx

Fix misspelled word

---

packages/web/spec/info/_category_.json
packages/web/spec/info/info.mdx
packages/web/spec/info/overview.mdx
packages/web/spec/info/resources.mdx
packages/web/src/schemas.ts
schemas/info.schema.yaml
schemas/info/resources.schema.yaml
schemas/materials/compilation.schema.yaml

Preview: https://info-preview-ethdebug-format.on-fleek.app/spec/info/

Define ethdebug/format/info schema

---

packages/web/spec/data/overview.mdx
packages/web/spec/data/value.mdx
packages/web/src/schemas.ts
schemas/data/value.schema.yaml
schemas/materials/source-range.schema.yaml
schemas/pointer/expression.schema.yaml
schemas/program/instruction.schema.yaml

To avoid schemas needing to use `oneOf` on the existing unsigned/hex schemas.

Define polymorphic value schema for numbers

---

packages/format/src/describe.ts

This feature was removed in YAML 1.2, but the existing examples use it, so turning this flag on for now.

Parse schema YAML using anchor merges from 1.1

---

schemas/program/context/variables.schema.yaml

- Require at least one property for each variable
- Disallow other properties in variable

Make variables contexts a bit more strict

---

packages/web/package.json
packages/web/spec/program/example.mdx
packages/web/src/theme/ProgramExample/HighlightedInstruction.tsx
packages/web/src/theme/ProgramExample/Opcodes.css
packages/web/src/theme/ProgramExample/Opcodes.tsx
packages/web/src/theme/ProgramExample/ProgramExampleContext.tsx
packages/web/src/theme/ProgramExample/SourceContents.css
packages/web/src/theme/ProgramExample/SourceContents.tsx
packages/web/src/theme/ProgramExample/Variables.tsx
packages/web/src/theme/ProgramExample/Viewer.css
packages/web/src/theme/ProgramExample/Viewer.tsx
packages/web/src/theme/ProgramExample/dynamic.ts
packages/web/src/theme/ProgramExample/index.ts
packages/web/src/theme/ProgramExample/offsets.ts
packages/web/src/theme/ShikiCodeBlock/ShikiCodeBlock.tsx
packages/web/src/theme/ShikiCodeBlock/index.ts
packages/web/src/theme/ShikiCodeBlock/useHighlighter.ts
yarn.lock

This PR defines a custom-written example smart contract in a fictional language and sets up website code infrastructure for displaying this example as an interactive widget on its own page.
This uses the TypeScript types provided by the @ethdebug/format package and imports the Shiki syntax highlighter instead of using Docusaurus's default Prism.js, since Prism doesn't support decorations/highlighting for ranges that don't span entire lines.
[Preview deployment](https://program-example-preview-ethdebug-format.on-fleek.app/spec/program/example)

Build initial plumbing for showing example programs

---

packages/format/src/describe.ts
packages/format/src/types/data/index.test.ts
packages/format/src/types/materials/index.test.ts
packages/format/src/types/pointer/pointer.test.ts
packages/format/src/types/program/context.test.ts
packages/format/src/types/program/instruction.test.ts
packages/format/src/types/program/program.test.ts
packages/format/src/types/type/base.test.ts
packages/format/src/types/type/index.test.ts
packages/web/spec/type/overview.mdx

Recently-added tests do a whole bunch of schema-lookup using `describeSchema({ schema: { id }, pointer?: string })`, which is overly verbose because `describeSchema()` is very polymorphic to account for all the ways this function gets used in testing code and on the website.
For now, I'm leaving it as "probably pretty useful" that this function is so polymorphic, but I wanted to simplify the syntax for simply obtaining a schema object for a particular ethdebug/format schema, so this PR just adds a new polymorphism, `describeSchema({ schema: string; })` and treats that as equivalent to `schema: { id: string }`.

Improve ergonomics of the `describeSchema()` function used everywhere

---

packages/format/.gitignore
packages/format/bin/generate-schema-yamls.js
packages/format/package.json
packages/format/src/describe.ts
packages/format/src/schemas/index.ts

(I was trying to get the tests that live in `./packages/tests` to get moved to `./packages/format`, to avoid the need for an extra package, but those tests don't seem to want to run inside a commonjs package, even when doing `await import()` manually. Looks like that's a jest problem, but seems like that's a problem for a different PR)

Make some internal changes

---

packages/tests/package.json
packages/tests/src/loadSchemas.ts
yarn.lock

This package is used for testing schema validity, as well as to test that schema examples adhere to the schema itself.
- Switch to new BASIC output format
- Add required peer dependency

Upgrade @hyperjump/json-schema

---

schemas/program.schema.yaml
schemas/program/context.schema.yaml
schemas/program/instruction.schema.yaml

As per discussion [around here](https://matrix.to/#/!uDzRSTeqPjFVMZFtZp:matrix.org/$vMLDiSmjXFQvBkyuTCvMD1zg6hy1kvMk4aDUTd5RL9k?via=matrix.org&via=ethereum.org&via=ekpyron.org) in Matrix.chat

Allow empty context objects and treat omitted `"context"` properties as equivalent to empty values

---

schemas/pointer/expression.schema.yaml

Our CI spellchecker tripped over them :)

Fix tiny typos

---

.github/workflows/deploy-pr-previews.yml
.github/workflows/gh-pages.yml

This PR uses [this action](https://github.com/marketplace/actions/deploy-pr-preview) for doing preview deployments.
To make it easier to respect that repo's stated "gotchas", this PR also switches to [this action](https://github.com/JamesIves/github-pages-deploy-action) for the main deployment.

Use Github Pages for PR previews

---

packages/web/src/theme/JSONSchemaViewer/JSONSchemaElements/schemaComposition/InclusiveRequiredPropertiesSchema.tsx
packages/web/src/theme/JSONSchemaViewer/JSONSchemaElements/schemaComposition/allOfSchema.tsx
schemas/program/context.schema.yaml

... to provide better error-reporting when using general-purpose JSON Schema validators.

Switch to if/then style for context properties

---

packages/format/src/types/program/context.test.ts
packages/format/src/types/program/context.ts
packages/web/spec/program/context/frame.mdx
packages/web/spec/program/context/gather.mdx
packages/web/spec/program/context/pick.mdx
packages/web/spec/program/example.mdx
packages/web/src/schemas.ts
packages/web/src/theme/ProgramExample/Details.tsx
packages/web/src/theme/ProgramExample/SourceContents.css
packages/web/src/theme/ProgramExample/SourceContents.tsx
packages/web/src/theme/ProgramExample/Viewer.tsx
schemas/program/context.schema.yaml
schemas/program/context/frame.schema.yaml
schemas/program/context/gather.schema.yaml
schemas/program/context/pick.schema.yaml

To support ambiguity and such.
[Deploy preview](https://ethdebug.github.io/format/pr-preview/pr-144/)

Define a few new context properties

---

LICENSE
README.md
schemas/LICENSE

- License schemas with CC0 (public domain)
- License everything else with MIT

Add LICENSE files for code+schemas
